### ISSUE TITLE
YML file for the provisioners

### ISSUE THREAD

**Issue by empeje** [solo-io/packer-builder-arm-image#11]
I think JSON format is a little bit ugly to my eyes (maybe for you too). Can we have a YML support? If you can onboard me with the code stacks, I'll be happy to help.

**Comment by yuval-k** [comment]
Unfortunately the requirement for json comes from packer itself.. this project is only a plugin for packer

**Comment by yuval-k** [comment]
See a related issue in packer here: https://github.com/hashicorp/packer/issues/1768
Closing for now as we cannot help with that. feel free to re-open

**Comment by empeje** [comment]
Thanks @yuval-k
