### ISSUE TITLE
Create Github Binary Releases

### ISSUE THREAD

**Issue by drewgonzales360** [solo-io/packer-builder-arm-image#16]
Could you create github releases and post the binary for darwin, linux, etc? Lemme know if you need help!

**Comment by yuval-k** [comment]
I'll try to setup some form of CI hopefully in the next weekend.

**Comment by bcomnes** [comment]
Minor alternative:

Just run:

```
go get github.com/solo-io/packer-builder-arm-image
go build -o packer-builder-arm-image github.com/solo-io/packer-builder-arm-image
```

In your build directory and packer will pick up the plugin. 

https://github.com/bcomnes/raspi-packer/blob/master/build-packer.sh

**Comment by jangrewe** [comment]
Or clone the repo, change into the directory and run:
`docker run --rm -v "$PWD":/build -w /build golang:1.12 go build`
