### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JamieMagee** [solo-io/packer-builder-arm-image#19]
I'd like to package `packer-builder-arm-image` for the [Arch User Repository](https://aur.archlinux.org/), but it's missing a license, which prevents me from distributing it. Github has a help page [here](https://help.github.com/articles/licensing-a-repository/) with some good advice about choosing a license. Thanks!

**Comment by yuval-k** [comment]
will add one now. it will be apache like all other solo open source projects
