### ISSUE TITLE
[Question]: is armv6 hardfp supported?

### ISSUE THREAD

**Issue by caquino** [solo-io/packer-builder-arm-image#31]
Hi,

I'm trying to build some raspberry pi images that are dependent on hardfp which fails if using this builder with it's default parameters.

Is there any configuration option that allows to more closely emulate a raspberry pi0 CPU?

Thanks in advance

**Comment by yuval-k** [comment]
i'm not sure about the specifics, but you can use the `qemu_args` config options to specify arguments to qemu

**Comment by yuval-k** [comment]
I hope this answers the question.
closing for now; please open if needed.
