### ISSUE TITLE
Packer 1.5 support

### ISSUE THREAD

**Issue by hectorm** [solo-io/packer-builder-arm-image#41]
Packer 1.5 has made some breaking changes and this plugin needs to be updated in order to work.
See: https://www.packer.io/guides/hcl/component-object-spec

**Comment by yuval-k** [comment]
thanks for the reference; hoping to have some bandwidth for this after the new-year. In the meantime if anyone wants to do a PR, please feel free to do so

**Comment by yuval-k** [comment]
this is solved by your PR, thanks!
closing
