### ISSUE TITLE
Fail to build image with latest version

### ISSUE THREAD

**Issue by tommie-lie** [solo-io/packer-builder-arm-image#5]
Using a fresh clone of this repository and doing a `vagrant up` results in the following output:
```
    default: Attempting to build image
    default: + popd
    default: + popd
    default: + [[ ! -f /home/vagrant/.packer.d/plugins/packer-builder-arm-image ]]
    default: + echo 'Attempting to build image'
    default: + [[ -f /vagrant/example.json ]]
    default: + sudo packer build /vagrant/example.json
    default: arm-image output will be in this color.
    default: 0 error(s) occurred:
    default: Error: Unable to find build artifact.
    default: + [[ -f /home/vagrant/output-arm-image/image ]]
    default: + echo 'Error: Unable to find build artifact.'
    default: + exit
```

In other words, the image os not being built but packer-builder-arm-image does not report any errors.

I pinpointed the problem to 452015d4, and the line https://github.com/solo-io/packer-builder-arm-image/commit/452015d4013d3294857414a03d77b3dba6bd3bed#diff-7d55094d2095596359f9af68227cd7cfR174 which should really be `return warnings, nil` if `errs` has length `0`.
A pull request which fixes this problem for me will come shortly.

**Comment by yuval-k** [comment]
Thank you for catching that, not sure why I changed it originally.
feel free to open issues\PRs if there are more features you want to see
