### ISSUE TITLE
"no image mounts provided." with latest rpi download

### ISSUE THREAD

**Issue by sdwilsh** [solo-io/packer-builder-arm-image#75]
With the example in the README (but with a newer pi release), I get this error:
```
1 error(s) occurred:

* no image mounts provided. Please set the image mounts or image type.
```

Looking through the code, I was able to figure out that this was because the image type wasn't being figured out earlier.  I was able to get past this by adding `image_type` to my builder like so:
```
  {
    "type": "arm-image",
    "image_type": "raspberrypi",
    "iso_url": "http://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2020-05-28/2020-05-27-raspios-buster-lite-armhf.zip",
    "iso_checksum_type": "sha256",
    "iso_checksum": "f5786604be4b41e292c5b3c711e2efa64b25a5b51869ea8313d58da0b46afc64"
  }
```

I'm not sure if some auto-detection code needs to be updated (they changed the URL format, probably so they can prepare for 64-bit versions of the pi), or if the readme should be updated.

**Comment by yuval-k** [comment]
yea the name change. for future reference, in case auto detection doesn't work, you can set `image_type` manually to `raspberrypi`.
i'll add the new type to auto detection
