### ISSUE TITLE
question: how does this differ with mkaczanowski/packer-builder-arm

### ISSUE THREAD

**Issue by hansbogert** [solo-io/packer-builder-arm-image#77]
I was wondering if there are conceptual differences between this project and https://github.com/mkaczanowski/packer-builder-arm ?  If so, when should I use this project, and when should I use the other?

Thanks in advance.

**Comment by yuval-k** [comment]
I'm not too familiar with the other project. this is the description in https://www.packer.io/docs/builders/community-supported/:

> packer-builder-arm-image - simple builder lets you extend on existing system images.
> packer-builder-arm - flexible builder lets you extend or build images from scratch with variety of options (ie. custom partition table).

I did not write the description above, nor tried the project. if you give both a try, feel free to comment your thoughts!
I can say that the main focus in this project is simplicity and ease of use.

**Comment by hansbogert** [comment]
Only now I see that the other author actually addressed this:
https://github.com/hashicorp/packer/pull/8462
