### ISSUE TITLE
Changing URL in iso_url fails (v0.1.6)

### ISSUE THREAD

**Issue by sergerad** [solo-io/packer-builder-arm-image#86]
This is the same issue as [this](https://github.com/solo-io/packer-builder-arm-image/issues/34).

I get this error with v0.1.6 whenever I change the default iso_url value.

Whether the URL is completely bogus, or points to a valid zipped .img file, the same error occurs.

```
Error: Failed to prepare build: "arm-image"

1 error(s) occurred:

* no image mounts provided. Please set the image mounts or image type.
```

I have made sure the `iso_checksum` value is correct.
```
  "builders": [
    {
      "type": "arm-image",
      "iso_url": "....",
      "iso_checksum": "sha256:55f9b5382c4756102be859858dd493d006345899df82e836864d2c55f72ff159",
      "target_image_size": 5368709120
    }
  ],
```

Im running on Docker e.g.
```
docker run --rm \
--privileged \
-v ${PWD}:/build:ro \
-v ${PWD}/packer_cache:/build/packer_cache \
-v ${PWD}/output-arm-image:/build/output-arm-image \
docker.pkg.github.com/solo-io/packer-builder-arm-image/packer-builder-arm:${VERSION} build image.json
```

**Comment by sergerad** [comment]
Manually adding image_mounts to the JSON fixes the issue:
```
"image_mounts": ["/boot", "/"]
```

However, I then get an odd error considering the zip contains a single `.img` file:
```
==> arm-image: Copying source image.
==> arm-image: Image is a zip file.
==> arm-image: support for only zip files with one file.
Build 'arm-image' errored: step canceled or halted
```

**Comment by yuval-k** [comment]
there is auto detection for some urls if the contain certain patterns.
i.e. if your url contains the work "raspberry" then we guess the correct `image_mounts`.

closing as answered

**Comment by whiteadam** [comment]
I'd like to add that "raspbian" is also properly recognized locally.
eg: `"iso_url": "/build/raspbian-pre-ansible.img"` will detect the correct mount point where `"iso_url": "/build/pre-ansible.img"` will not
